/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AdminDeployerUpdated = ContractEventLog<{
  oldAdminDeployer: string;
  newAdminDeployer: string;
  0: string;
  1: string;
}>;
export type AdminWhitelistUpdated = ContractEventLog<{
  admins: string[];
  status: boolean;
  0: string[];
  1: boolean;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type PoolRegistered = ContractEventLog<{
  index: string;
  pool: [string, string, string, string, string];
  0: string;
  1: [string, string, string, string, string];
}>;

export interface PoolDirectoryV2 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PoolDirectoryV2;
  clone(): PoolDirectoryV2;
  methods: {
    _editAdminWhitelist(
      admins: string[],
      status: boolean
    ): NonPayableTransactionObject<void>;

    _editDeployerWhitelist(
      deployers: string[],
      status: boolean
    ): NonPayableTransactionObject<void>;

    _setDeployerWhitelistEnforcement(
      enforce: boolean
    ): NonPayableTransactionObject<void>;

    adminDeployer(): NonPayableTransactionObject<string>;

    adminWhitelist(arg0: string): NonPayableTransactionObject<boolean>;

    deployPool(
      name: string,
      implementation: string,
      enforceWhitelist: boolean,
      closeFactor: number | string | BN,
      liquidationIncentive: number | string | BN,
      priceOracle: string
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    deployerWhitelist(arg0: string): NonPayableTransactionObject<boolean>;

    enforceDeployerWhitelist(): NonPayableTransactionObject<boolean>;

    getAllPools(): NonPayableTransactionObject<
      [string, string, string, string, string][]
    >;

    getPoolsByAccount(account: string): NonPayableTransactionObject<{
      0: string[];
      1: [string, string, string, string, string][];
    }>;

    getPublicPools(): NonPayableTransactionObject<{
      0: string[];
      1: [string, string, string, string, string][];
    }>;

    getPublicPoolsByVerification(
      whitelistedAdmin: boolean
    ): NonPayableTransactionObject<{
      0: string[];
      1: [string, string, string, string, string][];
    }>;

    initialize(
      _enforceDeployerWhitelist: boolean,
      _deployerWhitelist: string[]
    ): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    poolExists(arg0: string): NonPayableTransactionObject<boolean>;

    pools(arg0: number | string | BN): NonPayableTransactionObject<{
      name: string;
      creator: string;
      comptroller: string;
      blockPosted: string;
      timestampPosted: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    setAdminDeployer(
      newAdminDeployer: string
    ): NonPayableTransactionObject<void>;

    setPoolName(
      index: number | string | BN,
      name: string
    ): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    AdminDeployerUpdated(cb?: Callback<AdminDeployerUpdated>): EventEmitter;
    AdminDeployerUpdated(
      options?: EventOptions,
      cb?: Callback<AdminDeployerUpdated>
    ): EventEmitter;

    AdminWhitelistUpdated(cb?: Callback<AdminWhitelistUpdated>): EventEmitter;
    AdminWhitelistUpdated(
      options?: EventOptions,
      cb?: Callback<AdminWhitelistUpdated>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    PoolRegistered(cb?: Callback<PoolRegistered>): EventEmitter;
    PoolRegistered(
      options?: EventOptions,
      cb?: Callback<PoolRegistered>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AdminDeployerUpdated", cb: Callback<AdminDeployerUpdated>): void;
  once(
    event: "AdminDeployerUpdated",
    options: EventOptions,
    cb: Callback<AdminDeployerUpdated>
  ): void;

  once(
    event: "AdminWhitelistUpdated",
    cb: Callback<AdminWhitelistUpdated>
  ): void;
  once(
    event: "AdminWhitelistUpdated",
    options: EventOptions,
    cb: Callback<AdminWhitelistUpdated>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "PoolRegistered", cb: Callback<PoolRegistered>): void;
  once(
    event: "PoolRegistered",
    options: EventOptions,
    cb: Callback<PoolRegistered>
  ): void;
}
